version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mindflow_development
    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    build: .
    command: ["rails", "server", "-b", "0.0.0.0"]
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env.development
    restart: unless-stopped

volumes:
  postgres_data:
  bundle_cache:
